name: Feature Request
description: Request a new feature to be added
title: "[Request] Replace with your question"
labels: enhancement
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    options:
    - label: I have searched the existing issues
      required: true

- type: checkboxes
  attributes:
    label: Do you have Youtube Premium?
    options:
    - label: Yes, I have Youtube Premium
      required: false

- type: textarea
  attributes:
    label: My feature request
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
  validations:
    required: false
